# Generated by Django 2.2.24 on 2021-11-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('upvotes_amount', models.IntegerField()),
                ('link', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
