# Generated by Django 2.2.24 on 2021-11-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='upvotes_amount',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
