# Generated by Django 2.2.24 on 2021-11-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_auto_20211108_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItem',
            new_name='Post',
        ),
    ]
